version: '3.8'
name: postgres-local

services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
    ports:
      - "5432:5432"
    volumes:
      - ./1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
volumes:
  db-data:
