spring:
    application:
        name: config-server
    profiles:
        active:
        - native
        # - vault
        # - git
    
    cloud:
        config:
            server:
                # vault:
                #     port: 8200
                #     host: localhost
                #     kv-version: 2
                # bootstrap: false
                native:
                    search-locations: classpath:/config
                # git:
                #     uri: ""
                
server:
    port: 8071

encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo 

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.apache.http: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
